# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a9e95f9ac4b78384ec53ae5fc81f916d364e6bcab9b5cb3a086e6855ffbdd239c4dad39e91410892bb67467b8ca4deb03e389192bc6eb72fc9c0bc4ad5a38fb

test:
  secret_key_base: c7d771f1bee053aca0e1c2591245e5e3b3c402b8784e2db81e0940b85b39f94ccf1cedd01040f56a408b9270e4cfafa071ea4abfb7412e78b2f90ca6234a4d64

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
